### PR TITLE
fix(erc721): properly handle receiver errors

### LINKED ISSUE #224: [Bug]: Handle receiver contract reverts in ERC-721
Our implementation of the `_check_on_erc721_received` function is not equivalent to its Solidity counterpart.

### PR DESCRIPTION
**Pull request by alexfertel**
Resolves #224 

The `FIXME`s added in the PR are tracked [here](https://github.com/OpenZeppelin/rust-contracts-stylus/issues/228).

- [x] Tests

### CODE REVIEW

**Comment by qalisander** [comment]
The pipeline is still failing

**Review by qalisander — APPROVED** [review]
Good job!

**Review by bidzyyys — APPROVED** [review]
Looks good 👍  
We need an issue for tracking improvements in `Revert` extensions for E2E.

**Comment by alexfertel** [comment]
@bidzyyys yeah, it's in the PR description!

**Pull request merged**
