### PR TITLE
feat : Erc20Vote and Erc721Vote And Vote  

### LINKED ISSUE #353: [Feature]: ERC20Votes extension.
### What is the feature you would like to see?

Add ERC20Votes extension ([solidity](https://docs.openzeppelin.com/contracts/5.x/api/token/erc20#ERC20Votes)).

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by Ifechukwudaniel**
Resolves #353 and #357 

#### PR Checklist

- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Ifechukwudaniel** [comment]
@bidzyyys

**Comment by Ifechukwudaniel** [comment]
@0xNeshi

**Comment by 0xNeshi** [comment]
You [pinged me](https://github.com/OpenZeppelin/rust-contracts-stylus/pull/406#issuecomment-2481864694) to review, but you may have forgotten to push your changes

**Comment by Ifechukwudaniel** [comment]
should  i keep working on this

**Comment by Ifechukwudaniel** [comment]
@0xNeshi

**Comment by qalisander** [comment]
Hey @Ifechukwudaniel ! Thanks for your contribution!
You can keep working on those extensions within this pr.
But you should consider to keep you changes granular. I would prefer to have this branch for Erc20Vote.
And later you can add `Erc721Vote` extension within separate pr.

**Comment by Ifechukwudaniel** [comment]
Will do so

**Pull request closed without merging**
